name: flutter_tdd
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_launcher_icons: ^0.8.1
  cupertino_icons: ^0.1.3
  http:

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  mockito:
  faker:

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png

flutter_icons:
  ios: true
  android: true
  image_path_android: assets/icons/android.png
  image_path_ios: assets/icons/ios.png
  adaptive_icon_background: assets/icons/background.png
  adaptive_icon_foreground: assets/icons/foreground.png